# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

warnings_are_errors: false #Modify once warnings are solved. Added temporarily 20171025

after_success:
  - Rscript -e 'covr::codecov()'
